# Single source of truth for UI strings: key -> (English, Russian, Kazakh).
# Run `python3 tools/strings_source.py` to regenerate values/, values-ru/ and values-kk/ strings.xml.
S = {
"app_name": ("Clock", "Часы", "Сағат"),
"tab_clock": ("Clock", "Часы", "Сағат"),
"tab_alarms": ("Alarms", "Будильники", "Оятқыштар"),
"tab_stopwatch": ("Stopwatch", "Секундомер", "Секундомер"),
"tab_timers": ("Timers", "Таймеры", "Таймерлер"),
"settings_title": ("Settings", "Настройки", "Баптаулар"),
"back": ("Back", "Назад", "Артқа"),
"close": ("Close", "Закрыть", "Жабу"),
"cancel": ("Cancel", "Отмена", "Бас тарту"),
"save": ("Save", "Сохранить", "Сақтау"),
"delete": ("Delete", "Удалить", "Жою"),
"remove": ("Remove", "Удалить", "Алып тастау"),
"clear": ("Clear", "Очистить", "Тазалау"),
"alarm_state_on": ("On", "Вкл.", "Қосулы"),
"alarm_state_off": ("Off", "Выкл.", "Өшірулі"),

# Clock / world clock
"world_clock": ("World clock", "Мировое время", "Әлем уақыты"),
"world_clock_empty": ("Add cities to compare time zones.", "Добавьте города, чтобы сравнить часовые пояса.", "Уақыт белдеулерін салыстыру үшін қалалар қосыңыз."),
"add_city": ("Add city", "Добавить город", "Қала қосу"),
"search_city": ("Search city", "Поиск города", "Қаланы іздеу"),
"search_no_results": ("Nothing found", "Ничего не найдено", "Ештеңе табылмады"),
"city_actions": ("Actions for %1$s", "Действия: %1$s", "Әрекеттер: %1$s"),
"move_up": ("Move up", "Переместить выше", "Жоғары жылжыту"),
"move_down": ("Move down", "Переместить ниже", "Төмен жылжыту"),
"sort": ("Sort", "Сортировка", "Сұрыптау"),
"sort_manual": ("My order", "Мой порядок", "Өз ретім"),
"sort_name": ("By name", "По названию", "Атауы бойынша"),
"sort_offset": ("By time", "По времени", "Уақыт бойынша"),
"day_today": ("Today", "Сегодня", "Бүгін"),
"day_tomorrow": ("Tomorrow", "Завтра", "Ертең"),
"day_yesterday": ("Yesterday", "Вчера", "Кеше"),
"offset_same": ("same time", "то же время", "уақыт бірдей"),
"offset_hours": ("%1$s%2$d h", "%1$s%2$d ч", "%1$s%2$d сағ"),
"offset_hours_minutes": ("%1$s%2$d h %3$d min", "%1$s%2$d ч %3$d мин", "%1$s%2$d сағ %3$d мин"),

# Alarms
"alarm_default_title": ("Alarm", "Будильник", "Оятқыш"),
"add_alarm": ("Add alarm", "Новый будильник", "Жаңа оятқыш"),
"edit_alarm": ("Edit alarm", "Изменить будильник", "Оятқышты өзгерту"),
"alarms_empty": ("No alarms yet. Tap + to add one.", "Будильников пока нет. Нажмите +, чтобы добавить.", "Әзірге оятқыш жоқ. Қосу үшін + түймесін басыңыз."),
"next_alarm_in": ("Next alarm in %1$s", "Следующий будильник через %1$s", "Келесі оятқыш %1$s кейін"),
"alarm_saved_in": ("Alarm set for %1$s from now", "Будильник сработает через %1$s", "Оятқыш %1$s кейін шырылдайды"),
"alarm_label": ("Label", "Название", "Атауы"),
"label_work": ("Work", "Работа", "Жұмыс"),
"label_meeting": ("Meeting", "Совещание", "Кеңес"),
"label_medicine": ("Medicine", "Лекарства", "Дәрі"),
"repeat": ("Repeat", "Повтор", "Қайталау"),
"repeat_once": ("Once", "Однократно", "Бір рет"),
"repeat_every_day": ("Every day", "Каждый день", "Күн сайын"),
"repeat_weekdays": ("Weekdays", "По будням", "Жұмыс күндері"),
"repeat_weekend": ("Weekends", "По выходным", "Демалыс күндері"),
"alarm_sound": ("Sound", "Сигнал", "Дыбыс"),
"ringtone_default": ("Default alarm sound", "Стандартный сигнал будильника", "Әдепкі оятқыш дыбысы"),
"ringtone_picker_title": ("Alarm sound", "Сигнал будильника", "Оятқыш дыбысы"),
"vibration": ("Vibration", "Вибрация", "Діріл"),
"gradual_volume": ("Gradually increase volume", "Плавное увеличение громкости", "Дыбысты біртіндеп күшейту"),
"snooze_length": ("Snooze length", "Интервал повтора", "Кейінге қалдыру аралығы"),
"snooze_count": ("Snooze repeats", "Количество повторов", "Қайталау саны"),
"snooze_off": ("Off", "Выкл.", "Өшірулі"),
"minutes_short": ("%1$d min", "%1$d мин", "%1$d мин"),
"delete_alarm": ("Delete alarm", "Удалить будильник", "Оятқышты жою"),
"delete_alarm_confirm": ("Delete this alarm?", "Удалить этот будильник?", "Бұл оятқышты жою керек пе?"),
"alarm_snoozed_until": ("Snoozed until %1$s", "Отложен до %1$s", "%1$s дейін кейінге қалдырылды"),
"alarm_snoozed_until_cancel": ("Snoozed until %1$s · tap to cancel", "Отложен до %1$s · нажмите для отмены", "%1$s дейін кейінге қалдырылды · болдырмау үшін басыңыз"),
"alarm_missed_title": ("Missed alarm", "Пропущенный будильник", "Өткізіп алынған оятқыш"),
"duration_minutes": ("%1$d min", "%1$d мин", "%1$d мин"),
"duration_hours_minutes": ("%1$d h %2$d min", "%1$d ч %2$d мин", "%1$d сағ %2$d мин"),
"duration_days_hours": ("%1$d d %2$d h", "%1$d дн. %2$d ч", "%1$d күн %2$d сағ"),

# Actions
"action_dismiss": ("Dismiss", "Выключить", "Өшіру"),
"action_snooze": ("Snooze", "Отложить", "Кейінге қалдыру"),
"action_snooze_minutes": ("Snooze %1$d min", "Отложить на %1$d мин", "%1$d минутқа кейінге қалдыру"),
"action_start": ("Start", "Старт", "Бастау"),
"action_pause": ("Pause", "Пауза", "Кідірту"),
"action_resume": ("Resume", "Продолжить", "Жалғастыру"),
"action_reset": ("Reset", "Сброс", "Тастау"),
"action_lap": ("Lap", "Круг", "Айналым"),
"action_stop": ("Stop", "Стоп", "Тоқтату"),
"action_restart": ("Restart", "Повторить", "Қайта бастау"),
"action_add_minute": ("+1 min", "+1 мин", "+1 мин"),

# Stopwatch
"current_lap": ("Lap %1$s", "Круг %1$s", "Айналым %1$s"),
"laps": ("Laps", "Круги", "Айналымдар"),
"lap_number": ("Lap %1$d", "Круг %1$d", "%1$d-айналым"),
"lap_fastest": ("fastest", "лучший", "ең жылдам"),
"lap_slowest": ("slowest", "худший", "ең баяу"),
"laps_count": ("Laps: %1$d", "Кругов: %1$d", "Айналымдар: %1$d"),
"recent_results": ("Recent results", "Последние результаты", "Соңғы нәтижелер"),

# Timers
"quick_start": ("Quick start", "Быстрый запуск", "Жылдам іске қосу"),
"custom_timer": ("Custom", "Другое время", "Басқа уақыт"),
"start_timer_for": ("Start timer for %1$s", "Запустить таймер на %1$s", "%1$s таймерін іске қосу"),
"timers_empty": ("No timers. Choose a preset above.", "Таймеров нет. Выберите время выше.", "Таймер жоқ. Жоғарыдан уақытты таңдаңыз."),
"timers_limit": ("Timer limit reached: %1$d", "Достигнут лимит таймеров: %1$d", "Таймерлер шегіне жеттіңіз: %1$d"),
"timer_default_title": ("Timer", "Таймер", "Таймер"),
"timer_default_name": ("Timer %1$s", "Таймер %1$s", "Таймер %1$s"),
"timer_label": ("Timer name", "Название таймера", "Таймер атауы"),
"timer_status_ready": ("Ready", "Готов", "Дайын"),
"timer_status_running": ("Running", "Идёт", "Жүріп жатыр"),
"timer_status_paused": ("Paused", "На паузе", "Кідіртілді"),
"timer_status_finished": ("Finished", "Завершён", "Аяқталды"),
"timer_finished_title": ("Time is up", "Время вышло", "Уақыт бітті"),
"timer_ends_at": ("Ends at %1$s", "Закончится в %1$s", "%1$s-де аяқталады"),
"timer_paused_at": ("Paused · %1$s left", "Пауза · осталось %1$s", "Кідіртілді · %1$s қалды"),
"delete_timer": ("Delete %1$s", "Удалить: %1$s", "Жою: %1$s"),
"unit_hours": ("Hours", "Часы", "Сағат"),
"unit_minutes": ("Minutes", "Минуты", "Минут"),
"unit_seconds": ("Seconds", "Секунды", "Секунд"),

# Settings
"settings_appearance": ("Appearance", "Оформление", "Сыртқы түрі"),
"theme_system": ("As in system", "Как в системе", "Жүйедегідей"),
"theme_light": ("Light", "Светлая", "Ашық"),
"theme_dark": ("Dark", "Тёмная", "Қараңғы"),
"dynamic_color": ("Dynamic colors (Material You)", "Динамические цвета (Material You)", "Динамикалық түстер (Material You)"),
"settings_time": ("Time format", "Формат времени", "Уақыт пішімі"),
"time_format_system": ("As in system", "Как в системе", "Жүйедегідей"),
"time_format_12": ("12-hour", "12-часовой", "12 сағаттық"),
"time_format_24": ("24-hour", "24-часовой", "24 сағаттық"),
"show_seconds": ("Show seconds", "Показывать секунды", "Секундтарды көрсету"),
"settings_language": ("Language", "Язык", "Тіл"),
"language_system": ("As in system", "Как в системе", "Жүйедегідей"),
"language_ru": ("Русский", "Русский", "Русский"),
"language_kk": ("Қазақша", "Қазақша", "Қазақша"),
"language_en": ("English", "English", "English"),
"settings_alarms_timers": ("Alarms and timers", "Будильники и таймеры", "Оятқыштар мен таймерлер"),
"default_snooze": ("Default snooze", "Повтор по умолчанию", "Әдепкі кейінге қалдыру"),
"timer_sound": ("Timer sound", "Сигнал таймера", "Таймер дыбысы"),
"timer_vibration": ("Timer vibration", "Вибрация таймера", "Таймер дірілі"),
"settings_permissions": ("Permissions", "Разрешения", "Рұқсаттар"),
"perm_notifications": ("Notifications", "Уведомления", "Хабарландырулар"),
"perm_notifications_rationale": ("Needed to show ringing alarms and finished timers, including on the lock screen.", "Нужны, чтобы показывать звонящий будильник и завершённый таймер, в том числе на заблокированном экране.", "Шырылдап тұрған оятқышты және аяқталған таймерді, соның ішінде құлыптаулы экранда көрсету үшін қажет."),
"perm_exact": ("Exact alarms", "Точные будильники", "Дәл оятқыштар"),
"perm_exact_rationale": ("Lets alarms and timers ring at the exact minute even in battery saving mode. Without it Android may delay them.", "Позволяет будильникам и таймерам срабатывать точно в срок даже в режиме экономии энергии. Без него Android может задерживать сигнал.", "Оятқыштар мен таймерлерге энергия үнемдеу режимінде де дәл уақытында шырылдауға мүмкіндік береді. Онсыз Android сигналды кешіктіруі мүмкін."),
"perm_fullscreen": ("Full-screen alarms", "Полноэкранный будильник", "Толық экранды оятқыш"),
"perm_fullscreen_rationale": ("Shows the alarm screen over the lock screen so you can turn it off with one tap.", "Показывает экран будильника поверх экрана блокировки, чтобы выключить его одним нажатием.", "Оятқыш экранын құлып экранының үстінен көрсетеді, оны бір рет басып өшіруге болады."),
"perm_granted": ("Allowed", "Разрешено", "Рұқсат етілген"),
"perm_denied": ("Not allowed", "Не разрешено", "Рұқсат етілмеген"),
"perm_allow": ("Allow", "Разрешить", "Рұқсат беру"),
"perm_open_settings": ("Open settings", "Открыть настройки", "Баптауларды ашу"),
"perm_fix": ("Allow", "Разрешить", "Рұқсат беру"),
"settings_about": ("About", "О приложении", "Қолданба туралы"),
"about_text": ("Works fully offline. No ads, no analytics, no accounts: all data stays on this device.", "Работает полностью офлайн. Без рекламы, аналитики и аккаунтов: все данные хранятся только на этом устройстве.", "Толығымен офлайн жұмыс істейді. Жарнамасыз, аналитикасыз, аккаунтсыз: барлық деректер тек осы құрылғыда сақталады."),

# Notification channels
"channel_alarms": ("Alarms", "Будильники", "Оятқыштар"),
"channel_alarms_desc": ("Ringing alarms", "Звонящие будильники", "Шырылдап тұрған оятқыштар"),
"channel_timer_done": ("Finished timers", "Завершённые таймеры", "Аяқталған таймерлер"),
"channel_timer_done_desc": ("A timer has reached zero", "Таймер дошёл до нуля", "Таймер нөлге жетті"),
"channel_timer_running": ("Running timers", "Идущие таймеры", "Жүріп жатқан таймерлер"),
"channel_timer_running_desc": ("Countdown of active timers", "Обратный отсчёт активных таймеров", "Белсенді таймерлердің кері санағы"),
"channel_alarm_status": ("Alarm status", "Состояние будильников", "Оятқыш күйі"),
"channel_alarm_fallback": ("Alarms (backup sound)", "Будильники (резервный сигнал)", "Оятқыштар (қосалқы дыбыс)"),
"channel_alarm_fallback_desc": ("Used only if the system blocks the normal alarm sound", "Используется, только если система заблокировала обычный сигнал", "Жүйе әдеттегі дыбысты бұғаттаған жағдайда ғана қолданылады"),
"channel_alarm_status_desc": ("Snoozed and missed alarms", "Отложенные и пропущенные будильники", "Кейінге қалдырылған және өткізіп алынған оятқыштар"),

# Widgets
"widget_compact_name": ("Clock", "Часы", "Сағат"),
"widget_extended_name": ("Clock and alarm", "Часы и будильник", "Сағат және оятқыш"),
"widget_compact_description": ("Large time with date", "Крупное время и дата", "Үлкен уақыт және күн"),
"widget_extended_description": ("Time, date, next alarm and quick buttons", "Время, дата, следующий будильник и быстрые кнопки", "Уақыт, күн, келесі оятқыш және жылдам түймелер"),
"widget_next_alarm": ("Alarm: %1$s", "Будильник: %1$s", "Оятқыш: %1$s"),
"widget_no_alarms": ("No active alarms", "Нет активных будильников", "Белсенді оятқыш жоқ"),
"widget_open_app": ("Open Clock", "Открыть «Часы»", "«Сағат» қолданбасын ашу"),

# Cities
"city_unknown": ("City", "Город", "Қала"),
"city_aktau": ("Aktau", "Актау", "Ақтау"),
"city_astana": ("Astana", "Астана", "Астана"),
"city_almaty": ("Almaty", "Алматы", "Алматы"),
"city_shymkent": ("Shymkent", "Шымкент", "Шымкент"),
"city_karaganda": ("Karaganda", "Караганда", "Қарағанды"),
"city_pavlodar": ("Pavlodar", "Павлодар", "Павлодар"),
"city_oskemen": ("Oskemen", "Усть-Каменогорск", "Өскемен"),
"city_atyrau": ("Atyrau", "Атырау", "Атырау"),
"city_oral": ("Oral", "Уральск", "Орал"),
"city_aktobe": ("Aktobe", "Актобе", "Ақтөбе"),
"city_kostanay": ("Kostanay", "Костанай", "Қостанай"),
"city_kyzylorda": ("Kyzylorda", "Кызылорда", "Қызылорда"),
"city_moscow": ("Moscow", "Москва", "Мәскеу"),
"city_saint_petersburg": ("Saint Petersburg", "Санкт-Петербург", "Санкт-Петербург"),
"city_yekaterinburg": ("Yekaterinburg", "Екатеринбург", "Екатеринбург"),
"city_omsk": ("Omsk", "Омск", "Омбы"),
"city_novosibirsk": ("Novosibirsk", "Новосибирск", "Новосібір"),
"city_tashkent": ("Tashkent", "Ташкент", "Ташкент"),
"city_bishkek": ("Bishkek", "Бишкек", "Бішкек"),
"city_dushanbe": ("Dushanbe", "Душанбе", "Душанбе"),
"city_ashgabat": ("Ashgabat", "Ашхабад", "Ашхабад"),
"city_baku": ("Baku", "Баку", "Баку"),
"city_tbilisi": ("Tbilisi", "Тбилиси", "Тбилиси"),
"city_yerevan": ("Yerevan", "Ереван", "Ереван"),
"city_minsk": ("Minsk", "Минск", "Минск"),
"city_kyiv": ("Kyiv", "Киев", "Киев"),
"city_istanbul": ("Istanbul", "Стамбул", "Стамбұл"),
"city_dubai": ("Dubai", "Дубай", "Дубай"),
"city_doha": ("Doha", "Доха", "Доха"),
"city_riyadh": ("Riyadh", "Эр-Рияд", "Эр-Рияд"),
"city_tehran": ("Tehran", "Тегеран", "Тегеран"),
"city_delhi": ("New Delhi", "Нью-Дели", "Нью-Дели"),
"city_urumqi": ("Urumqi", "Урумчи", "Үрімжі"),
"city_beijing": ("Beijing", "Пекин", "Бейжің"),
"city_hong_kong": ("Hong Kong", "Гонконг", "Гонконг"),
"city_singapore": ("Singapore", "Сингапур", "Сингапур"),
"city_bangkok": ("Bangkok", "Бангкок", "Бангкок"),
"city_seoul": ("Seoul", "Сеул", "Сеул"),
"city_tokyo": ("Tokyo", "Токио", "Токио"),
"city_sydney": ("Sydney", "Сидней", "Сидней"),
"city_auckland": ("Auckland", "Окленд", "Окленд"),
"city_london": ("London", "Лондон", "Лондон"),
"city_paris": ("Paris", "Париж", "Париж"),
"city_berlin": ("Berlin", "Берлин", "Берлин"),
"city_rome": ("Rome", "Рим", "Рим"),
"city_madrid": ("Madrid", "Мадрид", "Мадрид"),
"city_amsterdam": ("Amsterdam", "Амстердам", "Амстердам"),
"city_prague": ("Prague", "Прага", "Прага"),
"city_cairo": ("Cairo", "Каир", "Каир"),
"city_new_york": ("New York", "Нью-Йорк", "Нью-Йорк"),
"city_chicago": ("Chicago", "Чикаго", "Чикаго"),
"city_denver": ("Denver", "Денвер", "Денвер"),
"city_los_angeles": ("Los Angeles", "Лос-Анджелес", "Лос-Анджелес"),
"city_toronto": ("Toronto", "Торонто", "Торонто"),
"city_mexico_city": ("Mexico City", "Мехико", "Мехико"),
"city_sao_paulo": ("São Paulo", "Сан-Паулу", "Сан-Паулу"),
"city_buenos_aires": ("Buenos Aires", "Буэнос-Айрес", "Буэнос-Айрес"),
"city_honolulu": ("Honolulu", "Гонолулу", "Гонолулу"),
}

UNTRANSLATABLE = {"language_ru", "language_kk", "language_en"}


def escape(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace("'", "\\'").replace('"', '\\"'))


def render(index: int, header: str) -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {header} Generated by tools/strings_source.py -->", "<resources>"]
    for key, values in S.items():
        attrs = ' translatable="false"' if key in UNTRANSLATABLE else ""
        if index > 0 and key in UNTRANSLATABLE:
            continue
        lines.append(f'    <string name="{key}"{attrs}>{escape(values[index])}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import os
    root = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")
    for index, folder, header in [(0, "values", "English (default)."), (1, "values-ru", "Russian."), (2, "values-kk", "Kazakh.")]:
        os.makedirs(os.path.join(root, folder), exist_ok=True)
        with open(os.path.join(root, folder, "strings.xml"), "w", encoding="utf-8") as f:
            f.write(render(index, header))
    print(f"{len(S)} strings x 3 languages written")
